fix: bug when storing `string | null` values
Error:
~~~
ERROR TS2322: Type '~lib/string/String | null' is not assignable to type '~lib/string/String'.
       encoder.setString(name, value);
                               ~~~~~
 in ~lib/near-sdk-bindgen/index.ts(125,31)
~~~

Notes: 
The cast is safe due to the null check before it.